### ISSUE TITLE
2 Sets of Field Maps

### ISSUE THREAD

**Issue by cphaneuf** [cbinyu/Preprocessing_tools#3]
How does fMRI prep treat 2 sets of field maps? The documentation is unclear. Do the 2 sets of field maps get combined by fMRI prep, if one is taken before the EPI sequence and one is taken after? Is it recommended to submit only 1 set of field maps? If so, which set should be submitted? Relatedly, how are the quality of field maps assessed? Thanks in advance!

**Comment by pvelasco** [comment]
Hi @cphaneuf,

> How does fMRI prep treat 2 sets of field maps? The documentation is unclear. Do the 2 sets of field maps get combined by fMRI prep, if one is taken before the EPI sequence and one is taken after?

From reading the documentation and code for fMRIPrep, I think it uses all field maps "IntendedFor" a given functional run.  If there are two runs for each Phase Encoding direction, it averages them (as far as I know) and then it estimates the field.

However, fMRIPrep (and any other BIDS-compatible tool) uses field maps in the `fmap` folder to correct a given functional run ***only if it has that functional run in the corresponding*** `"IntendedFor"` ***field*** in the field map `.json` file.

> Is it recommended to submit only 1 set of field maps? If so, which set should be submitted? 

The `"IntendedFor"` field in the field map `.json` file is not filled in by `heudiconv` (the process that converts DICOM to NIfTI and organizes it according to the BIDS standard), so we (CBI) wrote a script to fill it in.  Currently, it only sets it for the first pair of field maps acquired in a given session.

So, if you have a session with two (or more) pairs of field maps and you select all of them for extraction, our script finds the first pair and adds the functional runs names to the `"IntendedFor"` field.  Bottom line, fMRIPrep will only use the first one.

The second one is acquired just in case there is something wrong with the first one, since the whole distortion correction relies on having a decent field map.

In principle, if both maps have good quality, you could use both sets (by setting the `"IntendedFor"` field in the `.json`s for the second set of field maps, to get a better estimation.  However, the field changes a little bit during the session (due to the heating of the scanner), so the distortions in the two sets of field maps are going to be a little different, and when you combine both sets (even after motion correction) they will not align perfectly, so the combined images will likely be a little more blurry than a single one, and that might affect the field map estimation (and, therefore, the distortion correction).  That's why I recommend using only one pair, and why I have set the extraction script to tag only one pair.

> Relatedly, how are the quality of field maps assessed? Thanks in advance!

Good question.  The best way to assess the quality of the field maps is by checking how well fMRIPrep corrects for the susceptibility distortions.  For each functional run, there is a figure in the fMRIPrep html report that shows the bold reference image before and after correction, with the outline of the brain segmentation (in red, obtained from the T1w image).  If the correction worked well, the edges of the brain and the grey/white matter surface if the corrected image should match the brain segmentation.
